services:
  transfer-api:
    build:
      context: .
      dockerfile: TransferService/TransferService.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=TransferDb;Username=postgres;Password=postgres
  
  notification-service:
    build:
      context: .
      dockerfile: NotificationService/NotificationService.API/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=NotificationDb;Username=postgres;Password=postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  pgdata: